---
version: '3'
services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.0.1
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # broker:
  #   image: confluentinc/cp-kafka:7.0.1
  #   container_name: broker
  #   ports:
  #   # To learn about configuring Kafka for access across networks see
  #   # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  broker:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1,test:1:1"

  # kafka-topics-ui:
  #   image: landoop/kafka-topics-ui
  #   container_name: kafka-topics-ui
  #   ports:
  #     - "8001:8000"
  #   depends_on:
  #     - broker
  #   environment:
  #     KAFKA_REST_PROXY_URL: 'broker:9092'
  #     PROXY: 'zookeeper:2181'

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "8002:9000"
    depends_on:
      - broker
    environment:
      KAFKA_BROKERCONNECT: 'broker:9092'
      JVM_OPTS: '-Xms32M -Xmx64M'
      SERVER_SERVLET_CONTEXTPATH: '/'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest 
    container_name: kafka-ui
    ports:
      - "8003:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092'
      # KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'host.docker.internal:9092'
      KAFKA_CLUSTERS_0_NAME: 'local'
      SERVER_SERVLET_CONTEXTPATH: '/'